<Workspace Version="0.8.1.1823" X="279.490058217348" Y="1003.38254864905" zoom="1.09570667624989" Name="Home" RunType="Automatic" RunPeriod="100" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Nodes.DSModelElementsSelection guid="7e9ae4f8-5f4b-4918-83af-b95beb6a5e96" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="-104.364353991256" y="-742.946316087319" isVisible="true" isUpstreamVisible="true" lacing="Disabled" />
    <DSIronPythonNode.PythonNode guid="16e9a89d-812a-4be1-a328-e844b008e157" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="435.448659633542" y="-658.895690514132" isVisible="true" isUpstreamVisible="true" lacing="Disabled" inputcount="2">
      <Script>#Copyright (c) 2015, zhangzbxyz
#Dynamo中文社区 http://dynamochina.com

import sys
import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
# Import geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)
# Import DocumentManager and TransactionManager

from System.Collections.Generic import *
# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

elements=[]
rooms=[]
roomlist=[]

rooms=UnwrapElement(IN[1])

try:
	for item in IN[0]:
		elements.append(UnwrapElement(item))
except:
	elements.append(UnwrapElement(IN[0]))


for ele in elements:
	point= ele.Location.Point
	flag=0
	for room in rooms:
		if room.IsPointInRoom(point):
			#fmly=family.GetType().Name
			roomlist.append(room.Id.ToString())
			flag=1
	if flag==0:
		roomlist.append(0)

OUT=roomlist</Script>
    </DSIronPythonNode.PythonNode>
    <DSRevitNodesUI.Categories guid="d9fb3575-7a18-4217-bbe8-ade8d689fda5" type="DSRevitNodesUI.Categories" nickname="Categories" x="-142.614797577604" y="-481.927115857612" isVisible="true" isUpstreamVisible="true" lacing="Disabled" index="721:Rooms" />
    <DSRevitNodesUI.ElementsOfCategory guid="acf042be-89fc-4aeb-8a66-33d2a7ab4019" type="DSRevitNodesUI.ElementsOfCategory" nickname="All Elements of Category" x="163.735107330404" y="-528.648829826974" isVisible="true" isUpstreamVisible="true" lacing="Disabled" />
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="7e9ae4f8-5f4b-4918-83af-b95beb6a5e96" start_index="0" end="16e9a89d-812a-4be1-a328-e844b008e157" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="d9fb3575-7a18-4217-bbe8-ade8d689fda5" start_index="0" end="acf042be-89fc-4aeb-8a66-33d2a7ab4019" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="acf042be-89fc-4aeb-8a66-33d2a7ab4019" start_index="0" end="16e9a89d-812a-4be1-a328-e844b008e157" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
</Workspace>